# AND (obydwa warunki muszą dać TRUE)
print("Operator AND")
print(True and True)
print(True and False)
print(False and True)
print(False and False)

# OR (jeden z warunków musi dać TRUE)
print("Operator FOR")
print(True or True)
print(True or False)
print(False or True)
print(False or False)

# NOT (zaprzeczenie)
print('Operator NOT')
print(not True)
print(not False)
